### ISSUE TITLE
ARC support

### ISSUE THREAD

**Issue by Coneko** [karelia/ConnectionKit#27]
The readme specifies ConnectionKit supports OSX 10.6 or later, which means ARC support is possible with weak reference support provided by [PLWeakCompatibility](https://github.com/plausiblelabs/PLWeakCompatibility).

I'm not requesting this, I just want to ask whether you would be willing to merge it in if I do it myself.

**Comment by mikeabdullah** [comment]
The major obstacle to this is that we still support the legacy runtime (32bit on the Mac), which ARC isn't compatible with. We'll drop it at some point and consider ARC then.

So I have to ask, what's your reason for wanting to do this? As a framework, ConnectionKit can be comfortably used in ARC projects. We don't do anything that breaks compatibility with weak references, and have no use for them (currently) internally. There'd be no real benefit from ARC's performance enhancements since CK spends the vast majority of its time sitting waiting for network responses.

All I can see is a slightly smaller, easier-to-maintain codebase. Is there something I've missed?

**Comment by Coneko** [comment]
You haven't missed anything, those are the only reasons that made me want to do that. Not a big problem though, thanks for the fast reply.

**Comment by mikeabdullah** [comment]
Thanks for the understanding. I'm updating the Readme to note this.
