### ISSUE TITLE
Concurrent transfers

### ISSUE THREAD

**Issue by gbrhaz** [karelia/ConnectionKit#29]
Is there any way of making transfers concurrent? I'm using an NSOperationQueue on my end, and files can be created concurrently, but transferring files is done one at a time. 

If it's not done, is it possible or impossible to implement?

**Comment by mikeabdullah** [comment]
In general, you should be able to ask `CK2FileManager` to perform as many concurrent operations as you feel like. It will spawn as many connections as are needed.

However, right now the FTP backend (`CK2FTPProtocol`) tends to crash/misbehave quite a bit when used in this manner, so is internally funnelled through a single serial behaviour.

If you can fix `libcurl` to stop the crashing, that would be ideal. I appreciate that's a big task. Alternatively, you could re-implement `CK2CURLBasedProtocol` to use a pool `CURLHandle` instances, rather than a single shared one.

**Comment by mikeabdullah** [comment]
FWIW, after a libcurl bugfix, we've turned back on the asynchronous FTP backend, so you should be able to perform as many concurrent transfers as you like now.
