### ISSUE TITLE
Private Key Authentication

### ISSUE THREAD

**Issue by fjaeger** [karelia/ConnectionKit#44]
I don't get private key authentication to work with ConnectionKit. Could you give some more information on how to use it? Everything else is working fantastically. 

Is there a special authentication method like CK2AuthenticationMethodPrivateKey or similar? Currently, I am simply responding to NSURLAuthenticationMethodHTTPBasic and NSURLAuthenticationMethodHTTPDigest with a [NSURLCredential ck2_credentialWithUser...] if the user provides a private key file, but this does not seem to work :-(

Any kind of help is highly appreciated.

**Comment by mikeabdullah** [comment]
Can you be more specific than "does not seem to work", please?

**Comment by fjaeger** [comment]
Whenever I provide credentials using [NSURLCredential ck2_credentialWithUser...], the server asks again for authentication. May it be possible that it requires some other kind of authentication first, that I do not provide as I always provide the private key authentication credentials?
That's why I was asking whether there is a way to see whether the server requests a private key authentication at that particular stage?!

**Comment by mikeabdullah** [comment]
OK, there's a wealth of information available in each authentication challenge. How many previous attempts do they report? Any error info?

In practice right now, ConnectionKit asks the delegate for authentication info before ever attempting a connection to the server, rather than querying the server for what it supports. That's a design to deal with limitations in libcurl's API though.

After trying a connection, you should either receive a followup authentication challenge reporting that auth failed. _Or_ a second challenge, this time to confirm the server's fingerprint.

Just to check, you've read through all of the docs at https://github.com/karelia/ConnectionKit, right? If there's anything missing from there, I'd like to add or clarify it.

**Comment by fjaeger** [comment]
I get the following error:

Error Domain=NSURLErrorDomain Code=-1013 "Authentication failure" UserInfo=0x100563770 {NSUnderlyingError=0x108186550 "Authentication failure", NSErrorFailingURLStringKey=sftp://files.easyint.it:2222/~/dummy.png, NSErrorFailingURLKey=sftp://files.easyint.it:2222/~/dummy.png, NSLocalizedDescription=Authentication failure, NSLocalizedFailureReason=Login denied}

If you would like to test it yourself, I can send your the credentials, which are working in Cyberduck btw.

**Comment by mikeabdullah** [comment]
Sure, send them along to mabdullah@karelia.com and I'll be happy to test. If you can include a sample project too, that's even better.

**Comment by mikeabdullah** [comment]
Fixed!
